services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: yarn dev
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules

volumes:
  postgres_data: