services:
  app:
    build:
      target: development
    volumes:
      - '..:/app'
      - '/app/node_modules'
      - '../.eslintrc.js:/app/.eslintrc.js'
      - '../.prettierrc:/app/.prettierrc'
      - '../tsconfig.json:/app/tsconfig.json'
    environment:
      - NODE_ENV=development