services:
  db:
    image: 'postgres:15.2'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: schoole
    ports:
      - '5431:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'

  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      MEMORY_OVERCOMMIT: '1'

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 'yaksincorporation/achivee'
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: null