services:
  db:
    image: 'postgres:15.2'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: schoole
    ports:
      - '5431:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      MEMORY_OVERCOMMIT: '1'
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
      target: '${NODE_ENV}'
    depends_on:
      - db
    command: pnpm dev
    env_file:
      - ../.env
    ports:
      - '5000:5000'
    volumes:
      - '.:/usr/src/app'
      - './uploads:/usr/src/app/uploads'
      - '/usr/src/app/node_modules'
volumes:
  postgres_data: null
